[package]
name = "turkish_tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
unicode-segmentation = "1.10"
rayon = "1.8"
log = "0.4"
env_logger = "0.10"
regex = "1.10.2"
lazy_static = "1.4.0"
